language: node_js
node_js:
- 12
- 14
- 16
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.7
before_install:
- pip install aws-sam-cli
- pip install cfn-lint==0.60.0
