name: mapbox/cloudfriend
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        node-version: [14, 16, 18]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.7.17'
      - name: pip install
        run: |
          pip install -r requirements.dev.txt
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Retrieve and Configure NPM Token
        uses: mapbox/setup-npm-token@v1.4.0
      - run: |
          npm ci
      - run: |
          npm run test
